CREATE INDEX "age_group_doctorId_idx" ON "Age_Group" USING btree ("doctor_id");--> statement-breakpoint
CREATE INDEX "appointment_personId_idx" ON "Appointment" USING btree ("person_id");--> statement-breakpoint
CREATE INDEX "appointment_doctorId_idx" ON "Appointment" USING btree ("doctor_id");--> statement-breakpoint
CREATE INDEX "appointment_status_idx" ON "Appointment" USING btree ("status");--> statement-breakpoint
CREATE INDEX "appointment_startDateTime_idx" ON "Appointment" USING btree ("start_date_time");--> statement-breakpoint
CREATE INDEX "education_doctorId_idx" ON "Education" USING btree ("doctor_id");--> statement-breakpoint
CREATE INDEX "education_institutionId_idx" ON "Education" USING btree ("institution_id");--> statement-breakpoint
CREATE INDEX "institution_type_idx" ON "Institution" USING btree ("type");--> statement-breakpoint
CREATE INDEX "institution_placeId_idx" ON "Institution" USING btree ("place_id");--> statement-breakpoint
CREATE INDEX "institution_isVerified_idx" ON "Institution" USING btree ("is_verified");--> statement-breakpoint
CREATE INDEX "payment_method_person_personId_idx" ON "Payment_Method_Person" USING btree ("person_id");--> statement-breakpoint
CREATE INDEX "payment_method_person_paymentMethodId_idx" ON "Payment_Method_Person" USING btree ("payment_method_id");--> statement-breakpoint
CREATE INDEX "payment_method_person_isPreferred_idx" ON "Payment_Method_Person" USING btree ("is_preferred");--> statement-breakpoint
CREATE INDEX "payment_personId_idx" ON "Payment" USING btree ("person_id");--> statement-breakpoint
CREATE INDEX "payment_paymentMethodId_idx" ON "Payment" USING btree ("payment_method_id");--> statement-breakpoint
CREATE INDEX "payment_payoutMethodId_idx" ON "Payment" USING btree ("payout_method_id");--> statement-breakpoint
CREATE INDEX "payment_date_idx" ON "Payment" USING btree ("date");--> statement-breakpoint
CREATE INDEX "payout_method_doctorId_idx" ON "Payout_Method" USING btree ("doctor_id");--> statement-breakpoint
CREATE INDEX "payout_method_isPreferred_idx" ON "Payout_Method" USING btree ("is_preferred");--> statement-breakpoint
CREATE INDEX "person_placeId_idx" ON "Person" USING btree ("place_id");--> statement-breakpoint
CREATE INDEX "person_isActive_idx" ON "Person" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "phone_personId_idx" ON "Phone" USING btree ("person_id");--> statement-breakpoint
CREATE INDEX "phone_doctorId_idx" ON "Phone" USING btree ("doctor_id");--> statement-breakpoint
CREATE INDEX "progress_personId_idx" ON "Progress" USING btree ("person_id");--> statement-breakpoint
CREATE INDEX "progress_doctorId_idx" ON "Progress" USING btree ("doctor_id");--> statement-breakpoint
CREATE INDEX "progress_appointmentId_idx" ON "Progress" USING btree ("appointment_id");--> statement-breakpoint
CREATE INDEX "progress_conditionId_idx" ON "Progress" USING btree ("condition_id");--> statement-breakpoint
CREATE INDEX "review_score_idx" ON "Review" USING btree ("score");--> statement-breakpoint
CREATE INDEX "schedule_doctorId_idx" ON "Schedule" USING btree ("doctor_id");--> statement-breakpoint
CREATE INDEX "schedule_day_idx" ON "Schedule" USING btree ("day");