import { FcGoogle } from "react-icons/fc";
import { VscStarFull } from "react-icons/vsc";
import {
  Aperture,
  ArrowRight,
  ArrowUpDown,
  Brain,
  CalendarCheck,
  ChevronLeft,
  ClipboardPenLine,
  CommandIcon,
  Copy,
  CreditCard,
  Ellipsis,
  Eye,
  FileText,
  Heart,
  HeartHandshake,
  LayoutDashboard,
  Loader2,
  LogOut,
  MapPin,
  Pencil,
  Plus,
  Settings,
  Trash,
  User,
  Users,
  MessageSquare,
  UserRoundPen,
  X,
  type LucideIcon,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  aperture: Aperture,
  arrowRight: ArrowRight,
  booking: ClipboardPenLine,
  calendar: CalendarCheck,
  chevronLeft: ChevronLeft,
  close: X,
  command: CommandIcon,
  copy: Copy,
  creditCard: CreditCard,
  dashboard: LayoutDashboard,
  delete: Trash,
  edit: Pencil,
  ellipsis: Ellipsis,
  eye: Eye,
  file: FileText,
  google: FcGoogle,
  heart: Heart,
  heartHandshake: HeartHandshake,
  logout: LogOut,
  map: MapPin,
  message: MessageSquare,
  mind: Brain,
  payments: CreditCard,
  plus: Plus,
  profile: UserRoundPen,
  settings: Settings,
  sort: ArrowUpDown,
  spinner: Loader2,
  star: VscStarFull,
  user: User,
  users: Users,
};
